### PR TITLE
update to v0.19

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
The webtorrent devs provide also a zip tarball release, shouldn't be used instead of the deb file?

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
> The webtorrent devs provide also a zip tarball release, shouldn't be used instead of the deb file?

Generally the main difference between the zips and debs of Electron projects is that the `deb` file adds a `.desktop` file and icons to the expected places.

**Comment by bilelmoussaoui** [comment]
@TingPing Totally forgot about that :) Can this be merged, I'm getting a message everytime I open the application :P

**Pull request merged**
